### ISSUE TITLE
A stack-buffer-overflow vulnerability  in libdoipserver

### ISSUE THREAD

**Issue by gazer-star** [AVL-DiTEST-DiagDev/libdoip#8]
## Describe
we found stack-buffer-overflow in func `createVehicleIdentificationResponse` (libdoipserver/src/VehicleIdentificationHandler.cpp:16:37), when accessing the `VIN`, because the lack of the length checking 

<img width="821" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/b30eb8ba-7413-4056-bcbb-69d1e4f1088e">

<img width="399" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/5c4301d0-4285-46e9-ba10-da8dc4f17903">

## Asan Log
```
Broadcast Address set succesfully
Broadcast Option set successfully
=================================================================
==384843==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe8fee28e0 at pc 0x0000004d49ec bp 0x7ffe8fee2830 sp 0x7ffe8fee2828
READ of size 1 at 0x7ffe8fee28e0 thread T0
    #0 0x4d49eb in createVehicleIdentificationResponse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short, unsigned char*, unsigned char*, unsigned char) /home/user/Doip/libdoip/libdoipserver/src/VehicleIdentificationHandler.cpp:16:37
    #1 0x4d00f9 in DoIPServer::sendVehicleAnnouncement() /home/user/Doip/libdoip/libdoipserver/src/DoIPServer.cpp:249:30
    #2 0x4cc30c in main /home/user/Doip/libdoip/examples/exampleDoIPServer.cpp:121:12
    #3 0x7ffa1b354082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #4 0x41dafd in _start (/home/user/Doip/libdoip/build/exampleDoIPServer+0x41dafd)

Address 0x7ffe8fee28e0 is located in stack of thread T0 at offset 96 in frame
    #0 0x4cfaff in DoIPServer::sendVehicleAnnouncement() /home/user/Doip/libdoip/libdoipserver/src/DoIPServer.cpp:225

  This frame has 2 object(s):
    [32, 40) '__dnew.i.i.i.i'
    [64, 96) 'agg.tmp' <== Memory access at offset 96 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/user/Doip/libdoip/libdoipserver/src/VehicleIdentificationHandler.cpp:16:37 in createVehicleIdentificationResponse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short, unsigned char*, unsigned char*, unsigned char)
Shadow bytes around the buggy address:
  0x100051fd44c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100051fd44d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100051fd44e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100051fd44f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100051fd4500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100051fd4510: f1 f1 f1 f1 f8 f2 f2 f2 00 00 00 00[f3]f3 f3 f3
  0x100051fd4520: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100051fd4530: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 f8 f2 f2 f2
  0x100051fd4540: f8 f2 f2 f2 f8 f2 f2 f2 f8 f3 f3 f3 00 00 00 00
  0x100051fd4550: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100051fd4560: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==384843==ABORTING
````

**Comment by marcr** [comment]
Issue has been resolved on dev branch. Thank you very much for reporting.
