### ISSUE TITLE
An SEGV vulnerability in libdoipserver

### ISSUE THREAD

**Issue by gazer-star** [AVL-DiTEST-DiagDev/libdoip#9]
## Bug Description
We found an SEGV  casused by a READ memory access: `routedClientAddress` in `DoIPConnection::sendDiagnosticAck`
<img width="769" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/b65b703c-1909-4e3a-8032-562c611826ef">
The `routedClientAddress` is not initialized properly

<img width="747" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/53b7274c-bd1e-4ad7-8c52-893c0db1e873">

when `case PayloadType::DIAGNOSTICMESSAGE` in  function ` DoIPConnection::reactOnReceivedTcpMessage`, 

<img width="744" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/954915d6-2e4f-4295-ba3f-515d6d62b659">

then call the function `notify_application` handler (as func `DiagnosticMessageReceived`)

<img width="643" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/462b2fee-4427-44ed-8952-b46727e84388">

thus trigger the memory access to the un`routedClientAddress`

<img width="534" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/123e2717-0ff0-4078-8aa6-d822f18dd897">
<img width="769" alt="image" src="https://github.com/AVL-DiTEST-DiagDev/libdoip/assets/131155516/b65b703c-1909-4e3a-8032-562c611826ef">

##  Asan  Log
```
=================================================================
==886126==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x0000004d3b99 bp 0x7fd7b47819f0 sp 0x7fd7b4781940 T2)
==886126==The signal is caused by a READ memory access.
==886126==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x4d3b99 in DoIPConnection::sendDiagnosticAck(unsigned short, bool, unsigned char) /home/user/protocolFuzz/Doip/libdoip/libdoipserver/src/DoIPConnection.cpp:225:35
    #1 0x4cb103 in DiagnosticMessageReceived(unsigned short) /home/user/protocolFuzz/Doip/libdoip/examples/exampleDoIPServer.cpp:58:17
    #2 0x4d1a99 in std::function<bool (unsigned short)>::operator()(unsigned short) const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688:14
    #3 0x4d1a99 in DoIPConnection::reactOnReceivedTcpMessage(GenericHeaderAction, unsigned long, unsigned char*) /home/user/protocolFuzz/Doip/libdoip/libdoipserver/src/DoIPConnection.cpp:148:24
    #4 0x4d1453 in DoIPConnection::receiveTcpMessage() /home/user/protocolFuzz/Doip/libdoip/libdoipserver/src/DoIPConnection.cpp:53:25
    #5 0x4cb847 in listenTcp() /home/user/protocolFuzz/Doip/libdoip/examples/exampleDoIPServer.cpp:94:26
    #6 0x7fd7b7fdbde3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
    #7 0x7fd7b80ef608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #8 0x7fd7b7cb6132 in clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/user/protocolFuzz/Doip/libdoip/libdoipserver/src/DoIPConnection.cpp:225:35 in DoIPConnection::sendDiagnosticAck(unsigned short, bool, unsigned char)
Thread T2 created by T0 here:
    #0 0x48258a in pthread_create (/home/user/protocolFuzz/Doip/libdoip/build/exampleDoIPServer+0x48258a)
    #1 0x7fd7b7fdc0a8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd70a8)
    #2 0x7fd7b7bbb082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

==886126==ABORTING
```

**Comment by marcr-avl** [comment]
Hi @gazer-star thank you very much for reporting this issue and the previous one. And also thanks for analysing the code path.
We'll try to get this fixed quickly.

**Comment by marcr** [comment]
Hi, quick update as I now had the time to look into it.
You can avoid this SEGV if the client sends a RoutingActivation request to initiate the DoIP connection before sending the first Diagnostic Message. Then the routedClientAddress gets initialized properly.

Anyway, the SEGV shouldn't happen if the RoutingActivation request is missing. We'll fix that.
